### ISSUE TITLE
Explain more

### ISSUE THREAD

**Issue by Yvem** [RobinBressan/json-git#6]
- Is it true git code or did you just borrow the API ?
- can it be linked to a real git repo ? (e.g. GitHub)
- How much memory does it take ? Is it usable in a normal, core i3 browser ?
- How much confidence can we expect from the merge operation ?
- How much of an experiment is it ? Do you use it ? Is it solid or just a demo ?
- Could you share a use case where this solution solves problem ? (I'm thinking of shared edition of a file)

**Comment by Yvem** [comment]
Nice work anyway !

**Comment by RobinBressan** [comment]
Hi!

Reading all your questions make me think you maybe missed the purpose of the lib. 

> Is it true git code or did you just borrow the API ?

It is a standalone Git, the data model is heavily inspired by the well-known Git. But it is dedicated to the versioning of JSON and only JSON. So it is not about files as you might be used to.

> can it be linked to a real git repo ? (e.g. GitHub)

There is no remote, it is full local. The idea might be to handle each user using it on a separate branch and sometimes to merge them.

> How much memory does it take ? Is it usable in a normal, core i3 browser ?

I don't have any clues about memory consumption for now as it is only a `0.1.0` written in 2 days. But I've tested it on a huge JSON (500 kb) and it was quite fast.

> How much confidence can we expect from the merge operation ?

As said into the README, the merge will always work as it prioritize the new version over the previous. You can still deal with conflicts if you wish. 
In the background, the merge command works this way:

* Let's take two branches : `master` and `dev`. We want to merge `dev` into `master`.
* First the lib will find their common ancestor commit. Let's call it `commit 0`
* The lib makes a diff between the head of `dev` and `commit 0`
* The lib makes a diff between the head of `master` and  `commit 0`
* It compares the two generated patches, if they overlap : conflicts.
* The lib applies the final patch to `master`

> How much of an experiment is it ? Do you use it ? Is it solid or just a demo ?

It was written fast but right. It is fully tested so I guess it is a minimum solid as you said. I am not using it in a project yet but I wish. Working on a client project, it would be a good fit on it. I hope people will give it a try to make it better.
If I have an opportunity to integrate it into a client project I would definitely do it, but remember it is only a `0.1.0` so I can't give you any `production ready` badges.

> Could you share a use case where this solution solves problem ? (I'm thinking of shared edition of a file)

As I said above, it is only about JSON, not files (but maybe I misunderstood your question). My current client is using a *versionized* JSON to keep versions of subtitles. Many people edit a same subtitle JSON and it is important to keep an history.

But you could also using it for JSON config which is edited through your frontend for example.

Hope this helps!

Best regards

**Comment by Yvem** [comment]
All clear, thanks !
